package com.github.awvalenti.arquiteturadesoftware.rpg1.versao5.arquiteturadefinida.logicajogo;

import static com.github.awvalenti.arquiteturadesoftware.rpg1.versao5.arquiteturadefinida.logicajogo.Elemento.*;

public enum TabuleiroFase {
	PRIMEIRO(new Elemento[][] {
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA},
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA},
				{GRAMA, GRAMA, GRAMA, MACA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA},
				{PORTAL, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA},
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA},
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, MACA},
				{GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA},
				{GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA},
				{GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, MACA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
				{GRAMA, PERSONAGEM, GRAMA, GRAMA, URTIGA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
		}
	),
	SEGUNDO(new Elemento[][] {
			{AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA},
			{AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, PERSONAGEM, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA},
			{GRAMA, AGUA, AGUA, MACA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA},
			{PORTAL, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA},
			{GRAMA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA},
			{AGUA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, URTIGA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, MACA},
			{AGUA, GRAMA, AGUA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA},
			{AGUA, GRAMA, AGUA, GRAMA, AGUA, AGUA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA},
			{AGUA, GRAMA, AGUA, GRAMA, GRAMA, MACA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
			{AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
		}
	),
	TERCEIRO(new Elemento[][] {
			{AGUA, AGUA, AGUA, MACA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA},
			{GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, MACA},
			{GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, AGUA},
			{GRAMA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, AGUA},
			{GRAMA, AGUA, GRAMA, AGUA, GRAMA, AGUA, GRAMA, AGUA, GRAMA, AGUA, AGUA, URTIGA, GRAMA, AGUA, AGUA},
			{GRAMA, GRAMA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, GRAMA, AGUA, AGUA, GRAMA, AGUA, AGUA, AGUA},
			{AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, MACA, AGUA, AGUA, GRAMA, AGUA, AGUA, AGUA},
			{PORTAL, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, GRAMA, AGUA, AGUA, AGUA},
			{GRAMA, AGUA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA, AGUA, AGUA, AGUA},
			{PERSONAGEM, GRAMA, GRAMA, AGUA, AGUA, MACA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA},
		}
	),
	QUARTO(new Elemento[][] {
			{AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, PERSONAGEM, GRAMA, GRAMA, GRAMA},
			{AGUA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
			{AGUA, AGUA, GRAMA, MACA, AGUA, GRAMA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA},
			{AGUA, GRAMA, GRAMA, AGUA, GRAMA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA},
			{AGUA, AGUA, GRAMA, AGUA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA},
			{AGUA, AGUA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, MACA},
			{AGUA, AGUA, GRAMA, AGUA, GRAMA, GRAMA, GRAMA, URTIGA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA},
			{AGUA, AGUA, GRAMA, AGUA, GRAMA, GRAMA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA},
			{AGUA, AGUA, PORTAL, GRAMA, AGUA, MACA, AGUA, AGUA, AGUA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA},
			{AGUA, AGUA, AGUA, AGUA, GRAMA, GRAMA, GRAMA, GRAMA, GRAMA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA},
		}
	),
	;
	
	private final Tabuleiro t;
	
	TabuleiroFase(Elemento[][] m) {
		t = new Tabuleiro(m);
	}
	
	public Tabuleiro getTabuleiro() {
		return t;
	}
}
